/**
 * Ball Don't Lie API Type Definitions
 * Based on the official OpenAPI spec
 */

/**
 * Common API Response Structure
 */
export interface ApiResponse<T> {
  data: T[];
  meta: {
    next_cursor?: number;
    per_page: number;
  };
}

/**
 * Player
 */
export interface Player {
  id: number;
  first_name: string;
  last_name: string;
  position: string;
  height: string | null;
  weight: string | null;
  jersey_number: string | null;
  college: string | null;
  country: string | null;
  draft_year: number | null;
  draft_round: number | null;
  draft_number: number | null;
  team: Team;
}

/**
 * Team
 */
export interface Team {
  id: number;
  conference: string;
  division: string;
  city: string;
  name: string;
  full_name: string;
  abbreviation: string;
}

/**
 * Game
 */
export interface Game {
  id: number;
  date: string;
  season: number;
  status: string;
  period: number;
  time: string;
  postseason: boolean;
  home_team_score: number;
  visitor_team_score: number;
  home_team: Team;
  visitor_team: Team;
}

/**
 * Player Stats (Game Log)
 */
export interface GameStats {
  id: number;
  min: string;
  fgm: number;
  fga: number;
  fg_pct: number;
  fg3m: number;
  fg3a: number;
  fg3_pct: number;
  ftm: number;
  fta: number;
  ft_pct: number;
  oreb: number;
  dreb: number;
  reb: number;
  ast: number;
  stl: number;
  blk: number;
  turnover: number;
  pf: number;
  pts: number;
  player: Player;
  team: Team;
  game: Game;
}

/**
 * Season Averages
 */
export interface SeasonAverage {
  player_id: number;
  season: number;
  games_played: number;
  min: string;
  fgm: number;
  fga: number;
  fg_pct: number;
  fg3m: number;
  fg3a: number;
  fg3_pct: number;
  ftm: number;
  fta: number;
  ft_pct: number;
  oreb: number;
  dreb: number;
  reb: number;
  ast: number;
  stl: number;
  blk: number;
  turnover: number;
  pf: number;
  pts: number;
}

/**
 * Player Injury
 */
export interface PlayerInjury {
  player_id: number;
  player_name: string;
  team: string;
  position: string;
  injury_status: string;
  injury_description: string;
  updated_at: string;
}

/**
 * Player Prop (from /nba/v2/odds/player_props or PrizePicks)
 */
export interface PlayerProp {
  id: string;
  player_id: number;
  player_name: string;
  team: string;
  opponent: string;
  game_id: number;
  game_date: string;
  stat_type: string;
  line: number;
  over_odds?: number;
  under_odds?: number;
  sportsbook: string;
  // Player image URL (from PrizePicks or NBA CDN)
  image_url?: string;
}

/**
 * Internal App Types
 */

/**
 * Projection (Generated by ENSEMBLE system)
 */
export interface Projection {
  player_id: number;
  stat_type: string;
  projected_value: number;
  confidence: number;        // 0-100
  volatility: number;        // 0-100
  minutes_risk: 'Low' | 'Medium' | 'High';
  rationale_short: string;
  recommendation?: 'OVER' | 'UNDER' | 'AVOID';
  ensemble_breakdown?: {
    recency: number;
    matchup: number;
    momentum: number;
    context: number;
    weights_used: number[];
  };
}

/**
 * Enhanced Player Prop (Prop + Projection + Edge)
 */
export interface EnhancedPlayerProp {
  prop: PlayerProp;
  projection: Projection;
  edge: number;
  player?: Player;
  seasonAverage?: SeasonAverage;
  recentGames?: GameStats[];
  injury?: PlayerInjury;
  opponent?: Team;
}

/**
 * Parlay Suggestion
 */
export interface ParlaySuggestion {
  id: string;
  legs: EnhancedPlayerProp[];
  combinedOdds: number;
  qualityScore: number;
  avgConfidence: number;
}

/**
 * Minutes Risk Assessment
 */
export interface MinutesRisk {
  level: 'Low' | 'Medium' | 'High';
  averageMinutes: number;
  stdDeviation: number;
  explanation: string;
}

/**
 * Splits Data
 */
export interface SplitsData {
  home: number;
  away: number;
  last5: number;
  last10: number;
  last20: number;
  vsOpponent: number | null;
}

/**
 * Parlay
 */
export interface Parlay {
  id: string;
  props: EnhancedPlayerProp[];
  combinedOdds: number;      // Mocked for MVP
  totalEdge: number;
  avgConfidence: number;
}

/**
 * API Error
 */
export interface ApiError {
  message: string;
  statusCode?: number;
}

/**
 * Betting Odds from a sportsbook
 */
export interface SportsbookOdds {
  sportsbook: string;
  player_id: number;
  player_name: string;
  stat_type: string;
  line: number;
  over_odds: number;
  under_odds: number;
  game_id: number;
}

/**
 * Combined odds from multiple sportsbooks for comparison
 */
export interface OddsComparison {
  player_id: number;
  player_name: string;
  stat_type: string;
  game_id: number;
  books: SportsbookOdds[];
  bestOver: { sportsbook: string; odds: number; line: number } | null;
  bestUnder: { sportsbook: string; odds: number; line: number } | null;
}

/**
 * Team Standing
 */
export interface TeamStanding {
  team: Team;
  conference: string;
  division: string;
  wins: number;
  losses: number;
  conference_rank: number;
  division_rank: number;
  win_pct: number;
  home_record: string;
  away_record: string;
  last_10: string;
  streak: string;
}

/**
 * League Leader Entry
 */
export interface LeagueLeader {
  player: Player;
  rank: number;
  value: number;
  stat_type: string;
}

/**
 * Stat Type Keys
 * Note: 'pra' is a composite key for Points + Rebounds + Assists
 */
export type StatTypeKey = 'pts' | 'reb' | 'ast' | 'pra' | 'fg3m' | 'stl' | 'blk' | 'turnover';

/**
 * Helper type for accessing stats by string key
 */
export type StatsRecord = {
  [K in StatTypeKey]: number;
} & {
  min: string;
};
